--
-- Title: load_log.psql
-- Description: file load history
--
create table hyena_load_log (
  id            bigserial    primary key,
  file_name     varchar(48)  unique not null,
  host_name     varchar(32)  not null,
  obs_time      timestamp    not null default CURRENT_TIMESTAMP,
  project       varchar(32)  not null
);

grant select, insert, update, delete on hyena_load_log to hyena_client;
grant usage, select on sequence hyena_load_log_id_seq to hyena_client;

create index load_log_obs_date on hyena_load_log(obs_time);

create unique index obs_time_host_project on hyena_load_log(obs_time, host_name, project);
